server:
  port: 81

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateWayService Saler
  cloud:
    gateway:
      routes:
        - id: manager-login-service
          uri: lb://manager-login-service
          predicates:
            - Path=/manager-login-service/**
        - id: manager-service
          uri: lb://manager-service
          predicates:
            - Path=/manager-service/**