server:
  port: 81

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateWayService_Saler
  cloud:
    gateway:
      routes:
        - id: saler-login-service
          uri: lb://saler-login-service
          predicates:
            - Path=/saler-login-service/**
        - id: saler-service
          uri: lb://saler-service
          predicates:
            - Path=/saler-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
    exposure:
      include: "*"
  endpoint:
    health:
    show-details: always