server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateWayService Saler
  cloud:
    gateway:
      routes:
        - id: saler-login-service
          uri: lb://saler-login-service
          predicates:
            - Path=/saler-login-service/**
        - id: saler-service
          uri: lb://saler-service
          predicates:
            - Path=/saler-service/**